export const customStyles = {
  fontFamily: '"Inter", "Helvetica", "Arial", sans-serif',
  fontColor: "#91939A",
  xAxisLabels: { fontSize: "12px", fontWeight: 600 },
  yAxisLabels: { fontSize: "12px", fontWeight: 600 },
  xAxisTicks: { fontSize: "12px", fontWeight: 600 },
  yAxisTicks: { fontSize: "12px", fontWeight: 600 },
  legend: { fontSize: "12px", fontWeight: 600 },
  referenceLine: { fontSize: "12px", fontWeight: 600 },
  barSize: 20,
  tooltipBorderRadius: "12px",
  tooltipBorderColor: "#ddd",
  tooltipBackgroundColor: "#fff",
  tooltipFontColor: "#484848",
  tooltipTitleFontSize: "14px",
  tooltipTextFontSize: "12px",
  tooltipDarkFontWeight: 600,
  tooltipLightFontWeight: 500,
};
